# Generated by Django 4.0.1 on 2022-12-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
    ]
